#!/usr/bin/env bash
# install-cli.sh — install the host-side `outo-models` CLI shim.
#
# The server ships as a container image, so pulling an image alone does NOT
# put an `outo-models` command on the host. This script writes a small
# wrapper to /usr/local/bin/outo-models that runs the CLI from the image via
# `podman run --rm`, with the mounts the CLI needs:
#
#   - /etc/outo-models (config written by `setup`)
#   - the outo-models-data volume (admin commands hit the DB directly)
#   - the host Podman API socket (start/stop/restart/status/update/reset)
#   - a TTY when interactive (the setup wizard needs one)
#
# Usage:
#   sudo bash install-cli.sh [tag]        # default tag: stable
#   curl -sSL <raw-url>/scripts/install-cli.sh | sudo bash
#
# Exit codes: 0 ok, 1 not root / podman missing, 64 usage error.

set -euo pipefail

if [[ $# -gt 1 ]]; then
    echo "usage: $0 [image-tag]" >&2
    exit 64
fi

tag="${1:-stable}"
image="ghcr.io/llaa33219/outo-models:${tag}"
dest="/usr/local/bin/outo-models"

if [[ "$(id -u)" != "0" ]]; then
    echo "[error] run with sudo: sudo bash install-cli.sh ${tag}" >&2
    exit 1
fi

if ! command -v podman >/dev/null 2>&1; then
    echo "[error] podman is not installed. See docs/install.md." >&2
    exit 1
fi

cat > "${dest}" <<EOF
#!/usr/bin/env bash
# outo-models host CLI shim — generated by install-cli.sh (${image}).
# Override the image with OUTO_IMAGE, e.g. for a dev build:
#   OUTO_IMAGE=ghcr.io/llaa33219/outo-models:dev outo-models status
set -euo pipefail

image="\${OUTO_IMAGE:-${image}}"
sock="\${OUTO_PODMAN_SOCK:-/run/podman/podman.sock}"
if [[ ! -S "\${sock}" ]]; then
    user_sock="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}/podman/podman.sock"
    [[ -S "\${user_sock}" ]] && sock="\${user_sock}"
fi

args=(run --rm --network=host
    -v /etc/outo-models:/etc/outo-models
    -v outo-models-data:/var/lib/outo-models)

# Without the host socket, container lifecycle commands (start/stop/…)
# cannot work; the CLI reports that cleanly on its own.
if [[ -S "\${sock}" ]]; then
    args+=(-v "\${sock}:/run/podman/podman.sock" -e OUTO_PODMAN_SOCKET=/run/podman/podman.sock)
fi

# The setup wizard needs an interactive TTY; piping must keep working.
if [[ -t 0 ]]; then
    args+=(-it)
fi

exec podman "\${args[@]}" "\${image}" "\$@"
EOF

chmod 0755 "${dest}"

echo "[done] installed ${dest} (image: ${image})"
echo "       next: outo-models setup"
