#!/usr/bin/env bash
# install-cli.sh — install the host-side `outo-models` CLI shim.
#
# The server ships as a container image, so pulling an image alone does NOT
# put an `outo-models` command on the host. This script writes a small
# wrapper to /usr/local/bin/outo-models that runs the CLI from the image via
# `podman run --rm`, with the mounts the CLI needs:
#
#   - /etc/outo-models (config written by `setup`)
#   - the outo-models-data volume (admin commands hit the DB directly)
#   - the host Podman API socket (start/stop/restart/status/update/reset)
#   - a TTY when interactive (the setup wizard needs one)
#
# Image resolution order inside the wrapper:
#   1. OUTO_IMAGE environment variable (per-invocation override)
#   2. the `image:` key in /etc/outo-models/config.yaml (what `setup` chose)
#   3. the default baked in at install time (this script's argument)
#
# The shim itself is updated by re-running this installer (idempotent);
# the CLI code it runs is updated by `outo-models update` (new image pull).
#
# Usage:
#   sudo bash install-cli.sh [tag]        # default tag: stable
#   curl -sSL <raw-url>/scripts/install-cli.sh | sudo bash
#   curl -sSL <raw-url>/scripts/install-cli.sh | sudo bash -s dev
#
# Exit codes: 0 ok, 1 not root / podman missing, 64 usage error.

set -euo pipefail

if [[ $# -gt 1 ]]; then
    echo "usage: $0 [image-tag]" >&2
    exit 64
fi

tag="${1:-stable}"
image="ghcr.io/llaa33219/outo-models:${tag}"
dest="/usr/local/bin/outo-models"

if [[ "$(id -u)" != "0" ]]; then
    echo "[error] run with sudo: sudo bash install-cli.sh ${tag}" >&2
    exit 1
fi

if ! command -v podman >/dev/null 2>&1; then
    echo "[error] podman is not installed. See docs/install.md." >&2
    exit 1
fi

cat > "${dest}" <<EOF
#!/usr/bin/env bash
# outo-models host CLI shim — generated by install-cli.sh (default: ${image}).
# Image resolution order: OUTO_IMAGE env > image: key in
# /etc/outo-models/config.yaml (chosen by the setup wizard) > the default
# above. Examples:
#   OUTO_IMAGE=ghcr.io/llaa33219/outo-models:dev outo-models status
set -euo pipefail

image="\${OUTO_IMAGE:-}"
config_file="\${OUTO_CONFIG:-/etc/outo-models/config.yaml}"
if [[ -z "\${image}" && -f "\${config_file}" ]]; then
    # Top-level 'image:' key only; strip quotes and surrounding whitespace.
    image=\$(sed -n 's/^image:[[:space:]]*//p' "\${config_file}" | head -1 | tr -d '"' | xargs)
fi
image="\${image:-${image}}"

sock="\${OUTO_PODMAN_SOCK:-/run/podman/podman.sock}"
if [[ ! -S "\${sock}" ]]; then
    user_sock="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}/podman/podman.sock"
    [[ -S "\${user_sock}" ]] && sock="\${user_sock}"
fi

args=(run --rm --network=host
    -v /etc/outo-models:/etc/outo-models
    -v outo-models-data:/var/lib/outo-models)

# Without the host socket, container lifecycle commands (start/stop/…)
# cannot work; the CLI reports that cleanly on its own.
if [[ -S "\${sock}" ]]; then
    args+=(-v "\${sock}:/run/podman/podman.sock" -e OUTO_PODMAN_SOCKET=/run/podman/podman.sock)
fi

# The setup wizard needs an interactive TTY; piping must keep working.
if [[ -t 0 ]]; then
    args+=(-it)
fi

# Pre-pull with a clear error instead of podman run's raw failure —
# this is the first thing a brand-new operator sees.
if ! podman image exists "\${image}" 2>/dev/null; then
    if ! podman pull --quiet "\${image}"; then
        cat >&2 <<'GUIDE'
[error] failed to pull the image above.

  If you have not cut a stable release yet, reinstall the shim against the
  dev track:
      curl -sSL https://raw.githubusercontent.com/llaa33219/outo-models/main/scripts/install-cli.sh | sudo bash -s dev
  Or point at any other image for this invocation only:
      OUTO_IMAGE=<image-ref> outo-models <command>
GUIDE
        exit 1
    fi
fi

exec podman "\${args[@]}" "\${image}" "\$@"
EOF

chmod 0755 "${dest}"

echo "[done] installed ${dest} (default image: ${image})"
echo "       next: outo-models setup"
