#!/usr/bin/env bash
# install-cli.sh — install the host-side `outo-models` CLI shim.
#
# The server ships as a container image, so pulling an image alone does NOT
# put an `outo-models` command on the host. This script writes a small
# wrapper to /usr/local/bin/outo-models that runs the CLI from the image via
# `podman run --rm`, with the mounts the CLI needs:
#
#   - /etc/outo-models (config written by `setup`)
#   - the outo-models-data volume (admin commands hit the DB directly)
#   - the host Podman API socket (start/stop/restart/status/update/reset)
#   - a TTY when interactive (the setup wizard needs one)
#
# Image resolution order inside the wrapper:
#   1. OUTO_IMAGE environment variable (per-invocation override)
#   2. the `image:` key in /etc/outo-models/config.yaml (what `setup` chose)
#   3. the default baked in at install time (this script's argument)
#
# The shim itself is updated by re-running this installer (idempotent);
# the CLI code it runs is updated by `outo-models update` (new image pull).
#
# Usage:
#   sudo bash install-cli.sh [tag]        # default tag: stable
#   curl -sSL <raw-url>/scripts/install-cli.sh | sudo bash
#   curl -sSL <raw-url>/scripts/install-cli.sh | sudo bash -s dev
#
# Exit codes: 0 ok, 1 not root / podman missing, 64 usage error.

set -euo pipefail

if [[ $# -gt 1 ]]; then
    echo "usage: $0 [image-tag]" >&2
    exit 64
fi

tag="${1:-stable}"
image="ghcr.io/llaa33219/outo-models:${tag}"
dest="/usr/local/bin/outo-models"

if [[ "$(id -u)" != "0" ]]; then
    echo "[error] run with sudo: sudo bash install-cli.sh ${tag}" >&2
    exit 1
fi

if ! command -v podman >/dev/null 2>&1; then
    echo "[error] podman is not installed. See docs/install.md." >&2
    exit 1
fi

# The wrapper bind-mounts /etc/outo-models, and podman does NOT create
# missing host bind-mount sources (statfs failure). It must exist, and the
# in-container app (uid 1000) must be able to write config.yaml into it —
# the shim typically runs rootless as the invoking user, not via sudo.
mkdir -p /etc/outo-models
chown 1000:1000 /etc/outo-models

cat > "${dest}" <<EOF
#!/usr/bin/env bash
# outo-models host CLI shim — generated by install-cli.sh (default: ${image}).
# Image resolution order: OUTO_IMAGE env > image: key in
# /etc/outo-models/config.yaml (chosen by the setup wizard) > the default
# above. Examples:
#   OUTO_IMAGE=ghcr.io/llaa33219/outo-models:dev outo-models status
set -euo pipefail

image="\${OUTO_IMAGE:-}"
config_file="\${OUTO_CONFIG:-/etc/outo-models/config.yaml}"
if [[ -z "\${image}" && -f "\${config_file}" ]]; then
    # Top-level 'image:' key only; strip quotes and surrounding whitespace.
    image=\$(sed -n 's/^image:[[:space:]]*//p' "\${config_file}" | head -1 | tr -d '"' | xargs)
fi
image="\${image:-${image}}"

sock="\${OUTO_PODMAN_SOCK:-/run/podman/podman.sock}"
if [[ ! -S "\${sock}" ]]; then
    user_sock="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}/podman/podman.sock"
    [[ -S "\${user_sock}" ]] && sock="\${user_sock}"
fi

args=(run --rm --network=host
    --userns=keep-id
    -v /etc/outo-models:/etc/outo-models
    -v outo-models-data:/var/lib/outo-models)

# Without the host socket, container lifecycle commands (start/stop/…)
# cannot work; the CLI reports that cleanly on its own.
if [[ -S "\${sock}" ]]; then
    args+=(-v "\${sock}:/run/podman/podman.sock" -e OUTO_PODMAN_SOCKET=/run/podman/podman.sock)
fi

# The setup wizard needs an interactive TTY; piping must keep working.
if [[ -t 0 ]]; then
    args+=(-it)
fi

# Moving tags (:stable/:dev/:latest) track the newest release — refresh them
# so the shim never runs a stale local copy. Pinned tags (e.g. :0.2.0-dev)
# are immutable by convention and skip this. Offline → keep the local copy.
ref_tag="\${image##*:}"
if [[ "\${ref_tag}" == "stable" || "\${ref_tag}" == "dev" || "\${ref_tag}" == "latest" ]]; then
    podman pull --quiet "\${image}" >/dev/null 2>&1 || true
fi

# Pre-pull with a clear error instead of podman run's raw failure —
# this is the first thing a brand-new operator sees.
if ! podman image exists "\${image}" 2>/dev/null; then
    if ! podman pull --quiet "\${image}"; then
        cat >&2 <<'GUIDE'
[error] failed to pull the image above.

  If you have not cut a stable release yet, reinstall the shim against the
  dev track:
      curl -sSL https://raw.githubusercontent.com/llaa33219/outo-models/main/scripts/install-cli.sh | sudo bash -s dev
  Or point at any other image for this invocation only:
      OUTO_IMAGE=<image-ref> outo-models <command>
GUIDE
        exit 1
    fi
fi

exec podman "\${args[@]}" "\${image}" "\$@"
EOF

chmod 0755 "${dest}"

# The setup wizard opens host firewall ports by invoking this script on the
# host. We embed it byte-identical to src/outo_models/assets/scripts/firewall-open.sh
# inside this installer so a single `curl | sudo bash` finishes the job
# without a second fetch — the embedded copy is verified by
# tests/unit/test_install_cli.py to prevent drift between the two files.
firewall_dest="/usr/local/share/outo-models/firewall-open.sh"
mkdir -p "$(dirname "${firewall_dest}")"
cat > "${firewall_dest}" <<'OUTO_FIREWALL_HEREDOC_END'
#!/usr/bin/env bash
# outo-models firewall port-opening script
#
# The CLI invokes this on the host side as a non-root user. When it runs
# unprivileged it `exec sudo bash "$0" "$@"`s itself so an interactive sudo
# prompt can appear — `sudo -n` would deadlock the wizard. The Python
# orchestrator never prefixes `sudo` and never inspects `geteuid`; elevation
# lives entirely in this script. After elevation the script is as
# idempotent as possible — invoking it multiple times with the same
# arguments never errors.
#
# Usage:
#   firewall-open.sh <kind> <port...>
#
# kind:
#   firewalld  : firewalld permanent rules + reload
#   ufw        : ufw allow
#   nftables   : add dport rules to a dedicated outo_models table/chain
#   none       : no firewall detected — print guidance and exit 0
#
# Exit codes:
#   0  : success (or no change)
#   1  : sudo not installed (cannot self-elevate)
#   64 : usage error (EX_USAGE)
#   otherwise : tool execution failure

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "usage: $0 <kind> <port...>" >&2
    exit 64
fi

kind=$1
shift

if [[ $# -eq 0 ]]; then
    echo "at least one port required" >&2
    exit 64
fi

# Arguments arrive as trusted argv, but defensively re-validate integers only.
for p in "$@"; do
    if ! [[ $p =~ ^[0-9]+$ ]] || (( p < 1 || p > 65535 )); then
        echo "invalid port: ${p}" >&2
        exit 64
    fi
done

# Self-elevation: the script is shipped as a world-readable file at
# /usr/local/share/outo-models/firewall-open.sh. The container invokes it
# directly (not via sudo), so on a non-root invocation we re-exec ourselves
# under sudo. The exec replaces this process — there is no return path, so
# the rest of the script only ever runs as root. An interactive password
# prompt is allowed; the wizard waits for it.
if [[ "$(id -u)" != "0" ]]; then
    if ! command -v sudo >/dev/null 2>&1; then
        echo "[error] sudo is not installed; re-run this script as root, or install sudo." >&2
        exit 1
    fi
    exec sudo bash "$0" "$@"
fi

add_firewalld() {
    local p
    for p in "$@"; do
        firewall-cmd --permanent --add-port="${p}/tcp"
    done
    firewall-cmd --reload
}

add_ufw() {
    local p
    for p in "$@"; do
        ufw allow "${p}/tcp"
    done
}

add_nftables() {
    # Create a dedicated table/chain and accumulate rules there. Skip rules
    # that already exist.
    nft add table inet outo_models 2>/dev/null || true
    nft add chain inet outo_models outo_models_input \
        '{ type filter hook input priority 0 ; policy accept ; }' 2>/dev/null || true
    for p in "$@"; do
        if nft list ruleset | grep -qE "tcp dport ${p}([[:space:]]|$)"; then
            echo "nftables: port ${p} already open"
        else
            nft add rule inet outo_models outo_models_input tcp dport "${p}" counter accept
        fi
    done
}

print_no_firewall_guidance() {
    cat <<'EOF'
No firewall was detected. You must open the externally reachable ports
(80, 443) yourself in the OS firewall or your cloud security group.
EOF
}

case "$kind" in
    auto)
        # Host-side detection — used when the caller (e.g. the container
        # shim) cannot probe the host firewall itself.
        if command -v firewall-cmd >/dev/null 2>&1 \
            && [[ "$(firewall-cmd --state 2>/dev/null)" == "running" ]]; then
            add_firewalld "$@"
        elif command -v ufw >/dev/null 2>&1 \
            && ufw status 2>/dev/null | grep -q "Status: active"; then
            add_ufw "$@"
        elif command -v nft >/dev/null 2>&1 && nft list ruleset >/dev/null 2>&1; then
            add_nftables "$@"
        else
            print_no_firewall_guidance
        fi
        ;;
    firewalld)
        add_firewalld "$@"
        ;;
    ufw)
        add_ufw "$@"
        ;;
    nftables)
        add_nftables "$@"
        ;;
    none)
        print_no_firewall_guidance
        ;;
    *)
        echo "unknown firewall kind: ${kind}" >&2
        exit 64
        ;;
esac
OUTO_FIREWALL_HEREDOC_END

chmod 0755 "${firewall_dest}"

echo "[done] installed ${dest} (default image: ${image})"
echo "       installed ${firewall_dest} (host firewall script)"
echo "       next: outo-models setup"
